### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

### Reading Data

Source: https://www.kaggle.com/rakannimer/billboard-lyrics

In [2]:
lyrics = pd.read_csv('Data/billboard-1964-2015-songs-lyrics/billboard_lyrics_1964-2015_utf-8.csv')

In [3]:
lyrics.columns = ['rank','song','artist','year','lyrics','source']

### A Quick Look At Data

In [4]:
lyrics.head()

,rank,song,artist,year,lyrics,source
0,1,wooly bully,sam the sham and the pharaohs,1965,sam the sham miscellaneous wooly bully wooly b...,3.0
1,2,i cant help myself sugar pie honey bunch,four tops,1965,sugar pie honey bunch you know that i love yo...,1.0
2,3,i cant get no satisfaction,the rolling stones,1965,,1.0
3,4,you were on my mind,we five,1965,when i woke up this morning you were on my mi...,1.0
4,5,youve lost that lovin feelin,the righteous brothers,1965,you never close your eyes anymore when i kiss...,1.0

In [5]:
lyrics.tail()

,rank,song,artist,year,lyrics,source
5095,96,el perdon,nicky jam and enrique iglesias,2015,enrique iglesias dime si es verdad me dijeron ...,3.0
5096,97,she knows,neyo featuring juicy j,2015,NaN,NaN
5097,98,night changes,one direction,2015,going out tonight changes into something red ...,1.0
5098,99,back to back,drake,2015,oh man oh man oh man not againyeah i learned ...,1.0
5099,100,how deep is your love,calvin harris and disciples,2015,i want you to breathe me in let me be your ai...,1.0

### A Sample Lyric

In [6]:
lyrics['lyrics'][0]

'sam the sham miscellaneous wooly bully wooly bully sam the sham  the pharaohs  domingo samudio uno dos one two tres quatro matty told hatty about a thing she saw had two big horns and a wooly jaw wooly bully wooly bully wooly bully wooly bully wooly bully hatty told matty lets dont take no chance lets not belseven come and learn to dance wooly bully wooly bully wooly bully wooly bully wooly bully matty told hatty thats the thing to do get you someone really to pull the wool with you wooly bully wooly bully wooly bully wooly bully wooly bully lseven  the letter l and the number 7 when typed they form a rough square l7 so the lyrics mean lets not be square'

### A Look At the "year" Column

In [7]:
year_dist = pd.DataFrame(lyrics.year.value_counts())
year_dist.columns = ['Count']
year_dist['Percentage'] = lyrics.year.value_counts(normalize=True)
year_dist

      Count  Percentage
2015    100    0.019608
1965    100    0.019608
2005    100    0.019608
2001    100    0.019608
1997    100    0.019608
1993    100    0.019608
1989    100    0.019608
1985    100    0.019608
1981    100    0.019608
1977    100    0.019608
1973    100    0.019608
1969    100    0.019608
2012    100    0.019608
2013    100    0.019608
2008    100    0.019608
2004    100    0.019608
2000    100    0.019608
1996    100    0.019608
1992    100    0.019608
1988    100    0.019608
1984    100    0.019608
1980    100    0.019608
1976    100    0.019608
1972    100    0.019608
2009    100    0.019608
1966    100    0.019608
2011    100    0.019608
1967    100    0.019608
2007    100    0.019608
2003    100    0.019608
1999    100    0.019608
1995    100    0.019608
1991    100    0.019608
1987    100    0.019608
1983    100    0.019608
1979    100    0.019608
1975    100    0.019608
1971    100    0.019608
2014    100    0.019608
1970    100    0.019608
2010    100    0.019608
2006    100    0.019608
2002    100    0.019608
1998    100    0.019608
1994    100    0.019608
1990    100    0.019608
1986    100    0.019608
1982    100    0.019608
1978    100    0.019608
1974    100    0.019608
1968    100    0.019608

<div class="alert alert-success">
Potential Problem with this Dataset: Good Distribution of Year
</div>

### Remove Invalid "year"

### Look At the "genre" Column

In [8]:
genre_dist = pd.DataFrame(lyrics.genre.value_counts())
genre_dist.columns = ['Count']
genre_dist['Percentage'] = lyrics.genre.value_counts(normalize=True)
genre_dist

AttributeError: 'DataFrame' object has no attribute 'genre'

<div class="alert alert-warning">
Potentail Problem with this Dataset: Need to Collect the Genres of these songs
</div>

### Number of Unique Artist

In [9]:
artist_dist = pd.DataFrame(lyrics.artist.value_counts())
artist_dist.columns = ['Count']
artist_dist['Percentage'] = lyrics.artist.value_counts(normalize=True)
artist_dist

                                         Count  Percentage
madonna                                     35    0.006863
elton john                                  26    0.005098
mariah carey                                25    0.004902
michael jackson                             22    0.004314
janet jackson                               22    0.004314
stevie wonder                               22    0.004314
whitney houston                             19    0.003725
taylor swift                                19    0.003725
rihanna                                     19    0.003725
the beatles                                 17    0.003333
pink                                        17    0.003333
kelly clarkson                              17    0.003333
britney spears                              16    0.003137
the black eyed peas                         16    0.003137
chicago                                     15    0.002941
usher                                       14    0.002745
aretha franklin                             14    0.002745
rod stewart                                 14    0.002745
katy perry                                  14    0.002745
maroon 5                                    13    0.002549
kool  the gang                              13    0.002549
phil collins                                13    0.002549
the rolling stones                          13    0.002549
boyz ii men                                 13    0.002549
r kelly                                     13    0.002549
olivia newtonjohn                           12    0.002353
aerosmith                                   12    0.002353
eminem                                      12    0.002353
billy joel                                  12    0.002353
the temptations                             12    0.002353
...                                        ...         ...
big mountain                                 1    0.000196
mims                                         1    0.000196
the allman brothers band                     1    0.000196
yung joc featuring nitti                     1    0.000196
disclosure featuring sam smith               1    0.000196
michael martin murphey                       1    0.000196
the tony rich project                        1    0.000196
shaggy featuring rikrok                      1    0.000196
mike jones                                   1    0.000196
kid cudi                                     1    0.000196
matchbox 20                                  1    0.000196
vic dana                                     1    0.000196
sly fox                                      1    0.000196
fat joe featuring ashanti                    1    0.000196
estelle featuring kanye west                 1    0.000196
shocking blue                                1    0.000196
far east movement featuring ryan tedder      1    0.000196
honey cone                                   1    0.000196
jamie walters                                1    0.000196
shontelle                                    1    0.000196
fat joe featuring nelly                      1    0.000196
house of pain                                1    0.000196
zedd featuring foxes                         1    0.000196
ace frehley                                  1    0.000196
2 chainz                                     1    0.000196
icona pop featuring charli xcx               1    0.000196
samantha mumba                               1    0.000196
phil collins and marilyn martin              1    0.000196
the supremes  the temptations                1    0.000196
snoop dogg featuring r kelly                 1    0.000196

[2473 rows x 2 columns]

In [10]:
len(lyrics.artist.value_counts())

2473

In [12]:
artist_dist.index

Index(['madonna', 'elton john', 'mariah carey', 'michael jackson',
       'janet jackson', 'stevie wonder', 'whitney houston', 'taylor swift',
       'rihanna', 'the beatles',
       ...
       'fat joe featuring nelly', 'house of pain', 'zedd featuring foxes',
       'ace frehley', '2 chainz', 'icona pop featuring charli xcx',
       'samantha mumba', 'phil collins and marilyn martin',
       'the supremes  the temptations', 'snoop dogg featuring r kelly'],
      dtype='object', length=2473)

### Checking Number of Null Values

In [13]:
lyrics.isnull().sum()

rank        0
song        0
artist      0
year        0
lyrics    187
source    187
dtype: int64

### Remove Rows With Missing Values

In [14]:
lyrics.dropna(inplace=True)

In [15]:
lyrics.shape

(4913, 6)

### Plot Distribution of Year

### Look for Specific Artist

In [16]:
lyrics.loc[lyrics.artist=='taylor swift',:]

,rank,song,artist,year,lyrics,source
4288,89,teardrops on my guitar,taylor swift,2007,drew looks at me i fake a smile so he wont se...,1.0
4340,41,our song,taylor swift,2008,i was riding shotgun with my hair undone in t...,1.0
4347,48,teardrops on my guitar,taylor swift,2008,drew looks at me i fake a smile so he wont se...,1.0
4380,81,love story,taylor swift,2008,we were both young when i first saw you i clo...,1.0
4404,5,love story,taylor swift,2009,we were both young when i first saw you i clo...,1.0
4410,11,you belong with me,taylor swift,2009,youre on the phone with your girlfriend shes ...,1.0
4475,76,white horse,taylor swift,2009,say youre sorry that face of an angel comes o...,1.0
4545,46,mine,taylor swift,2010,oh oh oh oh oh ohyou were in college working ...,1.0
4556,57,you belong with me,taylor swift,2010,youre on the phone with your girlfriend shes ...,1.0
4583,84,today was a fairytale,taylor swift,2010,today was a fairytale you were the prince i u...,1.0
4673,74,back to december,taylor swift,2011,im so glad you made time to see me hows life ...,1.0
4732,33,we are never ever getting back together,taylor swift,2012,i remember when we broke up the first time sa...,1.0
4815,16,i knew you were trouble,taylor swift,2013,once upon time a few mistakes ago i was in yo...,1.0
4870,71,22,taylor swift,2013,it feels like a perfect night to dress up lik...,1.0
4912,13,shake it off,taylor swift,2014,i stay up too late got nothing in my brain th...,1.0
5006,7,blank space,taylor swift,2015,nice to meet you where you been i could show ...,1.0
5017,18,shake it off,taylor swift,2015,i stay up too late got nothing in my brain th...,1.0
5028,29,style,taylor swift,2015,midnight you come and pick me up no headlight...,1.0
5056,57,wildest dreams,taylor swift,2015,he said lets get out of this town drive out o...,1.0

### Vectorizing the Lyrics

In [17]:
len(list(lyrics['lyrics']))

4913

In [81]:
lyrics_data = list(lyrics['lyrics'])
count_vect = CountVectorizer(token_pattern=r'\b\w+\b')
lyrics_mat = count_vect.fit_transform(lyrics_data)
lyrics_mat.toarray().shape

(4913, 42160)

In [82]:
count_vect.vocabulary_

{'sam': 31008,
 'the': 36071,
 'sham': 32028,
 'miscellaneous': 23535,
 'wooly': 40718,
 'bully': 5540,
 'pharaohs': 27610,
 'domingo': 10379,
 'samudio': 31066,
 'uno': 38506,
 'dos': 10557,
 'one': 26106,
 'two': 38099,
 'tres': 37645,
 'quatro': 28953,
 'matty': 22474,
 'told': 37062,
 'hatty': 16339,
 'about': 437,
 'a': 365,
 'thing': 36247,
 'she': 32127,
 'saw': 31183,
 'had': 15968,
 'big': 4199,
 'horns': 17561,
 'and': 1597,
 'jaw': 19125,
 'lets': 20627,
 'dont': 10440,
 'take': 35550,
 'no': 25093,
 'chance': 6503,
 'not': 25273,
 'belseven': 3953,
 'come': 7520,
 'learn': 20484,
 'to': 36912,
 'dance': 8845,
 'thats': 36045,
 'do': 10203,
 'get': 14582,
 'you': 41617,
 'someone': 33460,
 'really': 29367,
 'pull': 28803,
 'wool': 40716,
 'with': 40532,
 'lseven': 21831,
 'letter': 20628,
 'l': 20099,
 'number': 25516,
 '7': 295,
 'when': 40004,
 'typed': 38145,
 'they': 36222,
 'form': 13773,
 'rough': 30613,
 'square': 34042,
 'l7': 20100,
 'so': 33311,
 'lyrics': 21945,
 'mean': 22576,
 'be': 3493,
 'sugar': 35008,
 'pie': 27714,
 'honey': 17408,
 'bunch': 5571,
 'know': 19889,
 'that': 35988,
 'i': 17924,
 'love': 21540,
 'cant': 6028,
 'help': 16715,
 'myself': 24378,
 'nobody': 25103,
 'elsein': 11551,
 'out': 26657,
 'my': 24363,
 'life': 20735,
 'go': 14973,
 'leaving': 20527,
 'just': 19498,
 'your': 41856,
 'picture': 27706,
 'behind': 3821,
 'kissed': 19771,
 'it': 18755,
 'thousand': 36447,
 'timeswhen': 36807,
 'snap': 33241,
 'finger': 13121,
 'or': 26547,
 'wink': 40465,
 'eye': 12308,
 'arunning': 2209,
 'im': 18074,
 'tied': 36631,
 'apron': 1970,
 'strings': 34741,
 'theres': 36188,
 'nothing': 25292,
 'can': 5969,
 'docant': 10220,
 'myselfsugar': 24393,
 'weaker': 39746,
 'than': 35959,
 'man': 22157,
 'should': 32353,
 'fool': 13573,
 'in': 18164,
 'seewanna': 31716,
 'tell': 35836,
 'were': 39890,
 'through': 36494,
 'ive': 18986,
 'tried': 37670,
 'but': 5691,
 'every': 12038,
 'time': 36694,
 'see': 31620,
 'face': 12410,
 'all': 1209,
 'choked': 6894,
 'up': 38598,
 'insidewhen': 18447,
 'call': 5899,
 'name': 24482,
 'girl': 14692,
 'starts': 34261,
 'flame': 13268,
 'burning': 5618,
 'heart': 16490,
 'tearing': 35767,
 'apart': 1868,
 'matter': 22456,
 'how': 17679,
 'try': 37853,
 'cannot': 6019,
 'hidecause': 16987,
 'weak': 39740,
 'for': 13623,
 'elsesugar': 11561,
 'anything': 1814,
 'ask': 2245,
 'me': 22560,
 'want': 39424,
 'woke': 40607,
 'this': 36339,
 'morning': 23982,
 'on': 26065,
 'mind': 23293,
 'got': 15397,
 'troubles': 37746,
 'whoaoh': 40127,
 'worries': 40854,
 'wounds': 40895,
 'bind': 4252,
 'went': 39886,
 'corner': 8034,
 'ease': 11279,
 'pains': 27028,
 'yeah': 41158,
 'came': 5944,
 'home': 17275,
 'again': 760,
 'miiiind': 23238,
 'feelin': 12798,
 'down': 10638,
 'shooooooes': 32309,
 'said': 30909,
 'way': 39608,
 'shooooes': 32308,
 'ramble': 29168,
 'move': 24121,
 'walk': 39334,
 'away': 2502,
 'blues': 4631,
 'never': 24781,
 'close': 7227,
 'eyes': 12322,
 'anymore': 1763,
 'kiss': 19766,
 'lips': 21053,
 'tenderness': 35881,
 'like': 20915,
 'before': 3717,
 'fingertips': 13131,
 'youre': 41858,
 'trying': 37869,
 'hard': 16231,
 'show': 32387,
 'baby': 2774,
 'ityou': 18978,
 'lost': 21476,
 'lovin': 21777,
 'whoa': 40108,
 'now': 25350,
 'its': 18905,
 'gone': 15144,
 'wohnow': 40605,
 'welcome': 39842,
 'look': 21360,
 'reach': 29283,
 'starting': 34254,
 'criticize': 8413,
 'little': 21115,
 'things': 36275,
 'makes': 22110,
 'feel': 12784,
 'crying': 8539,
 'cause': 6320,
 'something': 33478,
 'beautifuls': 3596,
 'dyinyou': 11212,
 'wohbaby': 40599,
 'id': 17963,
 'knees': 19832,
 'if': 17992,
 'would': 40883,
 'only': 26239,
 'used': 38771,
 'we': 39738,
 'find': 13060,
 'everyday': 12053,
 'let': 20623,
 'slip': 33052,
 'awaybaby': 2516,
 'beg': 3761,
 'please': 28006,
 'need': 24674,
 'bring': 5293,
 'back': 2967,
 'backbring': 2975,
 'wohbring': 40600,
 'alone': 1310,
 'is': 18688,
 'making': 22115,
 'lonely': 21260,
 'always': 1449,
 'downtown': 10764,
 'youve': 42015,
 'noise': 25157,
 'hurry': 17840,
 'seems': 31673,
 'downtownjust': 10767,
 'listen': 21070,
 'music': 24297,
 'of': 25637,
 'traffic': 37507,
 'city': 7044,
 'linger': 21032,
 'sidewalk': 32539,
 'where': 40013,
 'neon': 24761,
 'signs': 32598,
 'are': 1992,
 'pretty': 28526,
 'lose': 21451,
 'lights': 20880,
 'much': 24181,
 'brighter': 5277,
 'there': 36131,
 'forget': 13720,
 'caresso': 6150,
 'will': 40338,
 'great': 15585,
 'finer': 13107,
 'place': 27844,
 'sure': 35194,
 'waiting': 39305,
 'youdont': 41695,
 'hang': 16160,
 'around': 2099,
 'problems': 28600,
 'surround': 35242,
 'movie': 24145,
 'shows': 32422,
 'maybe': 22497,
 'some': 33431,
 'places': 27861,
 'rhythm': 30014,
 'gentle': 14556,
 'bossa': 4923,
 'nova': 25338,
 'youll': 41779,
 'dancing': 8901,
 'em': 11574,
 'too': 37254,
 'night': 24890,
 'over': 26796,
 'happy': 16209,
 'bright': 5273,
 'tonight': 37115,
 'gonna': 15211,
 'alright': 1396,
 'nowdowntownand': 25380,
 'may': 22492,
 'somebody': 33434,
 'kind': 19729,
 'understand': 38348,
 'who': 40107,
 'needs': 24702,
 'hand': 16091,
 'guide': 15827,
 'them': 36080,
 'along': 1368,
 'ill': 18048,
 'our': 26638,
 'wait': 39293,
 'minute': 23500,
 'more': 23902,
 'everything': 12075,
 'anybody': 1755,
 'was': 39514,
 'younger': 41808,
 'today': 36943,
 'needed': 24680,
 'anybodys': 1758,
 'any': 1754,
 'these': 36220,
 'days': 9151,
 'selfassured': 31751,
 'changed': 6546,
 'opened': 26499,
 'doors': 10510,
 'feeling': 12799,
 'appreciate': 1948,
 'being': 3858,
 'round': 30626,
 'feet': 12839,
 'ground': 15713,
 'wont': 40678,
 'has': 16300,
 'oh': 25721,
 'many': 22288,
 'ways': 39670,
 'independence': 18241,
 'vanish': 38901,
 'haze': 16396,
 'then': 36102,
 'insecure': 18399,
 'done': 10397,
 'ooo': 26413,
 'carterlewis': 6217,
 'lookin': 21374,
 'hear': 16468,
 'heartbeat': 16499,
 'car': 6084,
 'walking': 39343,
 'highway': 17061,
 'closer': 7233,
 'ooowee': 26477,
 'poundin': 28337,
 'put': 28901,
 'arms': 2072,
 'glad': 14875,
 'mighty': 23235,
 'found': 13842,
 'asked': 2246,
 'meet': 22729,
 'ma': 21954,
 'knew': 19846,
 'wed': 39786,
 'going': 15088,
 'far': 12626,
 'guitar': 15841,
 'friends': 14065,
 'cryin': 8538,
 'nows': 25449,
 'preacher': 28422,
 'wedding': 39788,
 'bells': 3921,
 'chime': 6840,
 'mine': 23389,
 'chapel': 6598,
 'tears': 35769,
 'shed': 32130,
 'joy': 19394,
 'meaning': 22593,
 'contentment': 7859,
 'am': 1459,
 'lordjust': 21434,
 'plain': 27880,
 'simple': 32640,
 'bumble': 5543,
 'people': 27461,
 'pray': 28391,
 'prayed': 28396,
 'lord': 21428,
 'grow': 15747,
 'stronger': 34781,
 'as': 2211,
 'live': 21122,
 'from': 14119,
 'day': 9085,
 'dayi': 9123,
 'searched': 31559,
 'couldnt': 8110,
 'earth': 11267,
 'gain': 14351,
 'peace': 27359,
 'mindnow': 23342,
 'accord': 536,
 'yes': 41492,
 'gather': 14470,
 'sing': 32662,
 'praise': 28386,
 'lordyoull': 21442,
 'search': 31558,
 'mindtake': 23365,
 'burdens': 5592,
 'lighter': 20850,
 'surely': 35204,
 'sunshine': 35114,
 'cloudy': 7273,
 'cold': 7424,
 'outside': 26740,
 'moth': 24034,
 'well': 39845,
 'guess': 15813,
 'say': 31194,
 'what': 39948,
 'make': 22100,
 'talkin': 35594,
 'bout': 4996,
 'bees': 3707,
 'envy': 11835,
 'sweeter': 35365,
 'song': 33525,
 'birds': 4276,
 'trees': 37628,
 'money': 23772,
 'fortune': 13824,
 'fame': 12571,
 'riches': 30035,
 'claim': 7072,
 'even': 12000,
 'month': 23846,
 'talk': 35587,
 'since': 32653,
 've': 38918,
 'been': 3678,
 'doin': 10307,
 'head': 16406,
 'late': 20320,
 'at': 2321,
 'mornin': 23981,
 'lay': 20427,
 'bed': 3639,
 'rhonda': 30005,
 'fine': 13087,
 'wouldnt': 40888,
 'her': 16749,
 'wife': 40279,
 'another': 1697,
 'guy': 15904,
 'between': 4135,
 'us': 38751,
 'ruined': 30727,
 'plan': 27887,
 'caught': 6315,
 'give': 14841,
 'lotsa': 21495,
 'reasons': 29401,
 'why': 40208,
 'gotta': 15436,
 'trailer': 37517,
 'sale': 30982,
 'rent': 29751,
 'rooms': 30565,
 'fifty': 12975,
 'cents': 6426,
 'phone': 27645,
 'pool': 28187,
 'pets': 27596,
 'aint': 1055,
 'cigarettes': 7004,
 'ah': 949,
 'hours': 17651,
 'pushin': 28889,
 'broom': 5366,
 'buys': 5748,
 'an': 1582,
 'eight': 11454,
 'by': 5761,
 'twelve': 38037,
 'fourbit': 13865,
 'room': 30555,
 'means': 22601,
 'king': 19746,
 'roadthird': 30333,
 'boxcar': 5021,
 'midnight': 23218,
 'train': 37522,
 'destination': 9640,
 'bangor': 3280,
 'maine': 22084,
 'old': 26015,
 'worn': 40851,
 'clothes': 7258,
 'shoes': 32286,
 'pay': 27329,
 'union': 38464,
 'dues': 11110,
 'smoke': 33205,
 'stogies': 34514,
 'have': 16353,
 'short': 32331,
 'roadi': 30316,
 'engineer': 11739,
 'their': 36076,
 'children': 6815,
 'names': 24514,
 'handout': 16125,
 'town': 37432,
 'lock': 21210,
 'locked': 21213,
 'ones': 26154,
 'aroundi': 2122,
 'trailers': 37518,
 'road': 30308,
 'ya': 41052,
 'flowers': 13455,
 'moon': 23865,
 'above': 470,
 'called': 5904,
 'stars': 34216,
 'sky': 32889,
 'could': 8096,
 'into': 18581,
 'brown': 5388,
 'very': 39004,
 'learned': 20485,
 'facts': 12456,
 'z': 42088,
 'hold': 17223,
 'until': 38564,
 'thrill': 36475,
 'lane': 20240,
 'shadows': 31975,
 'hiding': 17009,
 'lovers': 21705,
 'same': 31011,
 'sensible': 31815,
 'new': 24792,
 'fooled': 13578,
 'thinking': 36309,
 'last': 20286,
 'stood': 34549,
 'dark': 8967,
 'drive': 10977,
 'slowly': 33093,
 'miss': 23560,
 'ever': 12013,
 'adieu': 646,
 'fade': 12460,
 'ì': 42158,
 'shotgun': 32346,
 'shoot': 32311,
 'he': 16405,
 'runs': 30794,
 'jerk': 19210,
 'heyì': 16965,
 'red': 29474,
 'dress': 10939,
 'buy': 5740,
 'yourself': 41884,
 'break': 5162,
 'load': 21186,
 'him': 17089,
 'nowì': 25484,
 'hey': 16884,
 'high': 17013,
 'heels': 16666,
 'goin': 15087,
 'here': 16755,
 'play': 27939,
 'dig': 9868,
 'potatoes': 28323,
 'pick': 27690,
 'tomatoes': 37070,
 'twine': 38066,
 'timeì': 36844,
 'young': 41804,
 'true': 37762,
 'babe': 2718,
 'earned': 11258,
 'moneys': 23798,
 'spent': 33861,
 'pot': 28321,
 'least': 20504,
 'spring': 34000,
 'wear': 39764,
 'ring': 30220,
 'sad': 30874,
 'clown': 7279,
 'scared': 31353,
 'hairs': 16026,
 'long': 21285,
 'care': 6105,
 'wrong': 40955,
 'hill': 17075,
 'mountain': 24099,
 'climb': 7183,
 'goodnight': 15310,
 'tight': 36646,
 'wants': 39450,
 'diamond': 9734,
 'took': 37276,
 'off': 25647,
 'doesnt': 10262,
 'shine': 32208,
 'did': 9769,
 'whose': 40199,
 'stone': 34529,
 'genuine': 14562,
 'babys': 2890,
 'truer': 37793,
 'beautiful': 3582,
 'dreams': 10899,
 'coming': 7563,
 'instrumental': 18498,
 'mrs': 24170,
 'lovely': 21650,
 'daughter': 9058,
 'girls': 14784,
 'sharp': 32094,
 'somethin': 33475,
 'rare': 29222,
 'shes': 32185,
 'made': 22008,
 'clear': 7138,
 'enough': 11759,
 'good': 15220,
 'pineshe': 27787,
 'return': 29931,
 'those': 36426,
 'bought': 4962,
 'keep': 19578,
 'callwalkin': 5926,
 'crowd': 8462,
 'bloke': 4551,
 'proudif': 28728,
 'finds': 13077,
 'broke': 5329,
 'pinewalkin': 27788,
 'pinemrs': 27784,
 'stop': 34556,
 'heartbaby': 16498,
 'aware': 2500,
 'each': 11235,
 'leave': 20510,
 'door': 10488,
 'watch': 39559,
 'street': 34688,
 'knowing': 19927,
 'other': 26603,
 'run': 30760,
 'hurt': 17842,
 'think': 36302,
 'after': 744,
 'sweet': 35362,
 'youstop': 41961,
 'overive': 26841,
 'known': 19950,
 'secluded': 31588,
 'nights': 24976,
 'seen': 31683,
 'once': 26088,
 'twice': 38050,
 'expression': 12275,
 'worth': 40870,
 'affection': 715,
 'rush': 30804,
 'charms': 6639,
 'havent': 16360,
 'patient': 27293,
 'hoping': 17538,
 'youd': 41685,
 'infatuation': 18286,
 'together': 36996,
 'afraid': 729,
 'losing': 21471,
 'foreverstop': 13701,
 'darling': 8997,
 'hungered': 17809,
 'touch': 37374,
 'goes': 15041,
 'still': 34458,
 'god': 15015,
 'speed': 33841,
 'byamandah': 5763,
 'editor': 11382,
 'written': 40954,
 '1955': 67,
 'unchained': 38294,
 'melody': 22849,
 'become': 3630,
 'mostrecorded': 24029,
 'songs': 33554,
 '20th': 124,
 'centurythe': 6435,
 'righteous': 30122,
 'brothers': 5381,
 'version': 38993,
 'remaining': 29663,
 'probably': 28591,
 'most': 24024,
 'rivers': 30294,
 'flow': 13446,
 'sea': 31531,
 'open': 26494,
 'sigh': 32563,
 'meoh': 22948,
 'mountains': 24100,
 'gaze': 14494,
 'dawn': 9070,
 'dayall': 9088,
 'dreaming': 10886,
 'slaycrewetook': 32972,
 'passed': 27237,
 'house': 17654,
 'shades': 31969,
 'pulled': 28804,
 'drawn': 10859,
 'within': 40540,
 'dim': 9908,
 'light': 20837,
 'cast': 6269,
 'silhouettes': 32618,
 'shade': 31965,
 'couple': 8148,
 'madeput': 22018,
 'his': 17142,
 'waist': 39289,
 'held': 16687,
 'kisses': 19773,
 'almost': 1308,
 'taste': 35683,
 'wondered': 40657,
 'whos': 40197,
 'hide': 16979,
 'eyesahahahahah': 12323,
 'ahahahahah': 957,
 'lead': 20452,
 'control': 7881,
 'rang': 29186,
 'bell': 3914,
 'sore': 33625,
 'else': 11538,
 'beat': 3541,
 'strangers': 34656,
 'shock': 32280,
 'blockrushed': 4545,
 'wings': 40445,
 'loved': 21569,
 'vowed': 39227,
 'shadeahahahahah': 31966,
 'world': 40798,
 'somewhere': 33507,
 'promised': 28650,
 'land': 20222,
 'someday': 33445,
 'handi': 16104,
 'beside': 4054,
 'youthere': 41982,
 'forever': 13662,
 'whole': 40163,
 'youits': 41761,
 'journey': 19388,
 'stay': 34299,
 'side': 32496,
 'storm': 34607,
 'guideif': 15830,
 'gave': 14483,
 'pleasure': 28039,
 'small': 33136,
 'tomorrow': 37084,
 'allbut': 1220,
 'dear': 9271,
 'youbut': 41660,
 'mantovani': 22277,
 'cara': 6085,
 'mia': 23173,
 'must': 24329,
 'goodbye': 15227,
 'part': 27184,
 'die': 9794,
 'prayer': 28397,
 'fair': 12489,
 'till': 36680,
 'end': 11649,
 'mr': 24168,
 'tambourine': 35618,
 'sleepy': 33009,
 'jingle': 19286,
 'jangle': 19105,
 'followin': 13555,
 'youtake': 41970,
 'trip': 37699,
 'upon': 38667,
 'magic': 22051,
 'swirling': 35413,
 'ship': 32230,
 'senses': 31814,
 'stripped': 34747,
 'hands': 16127,
 'grip': 15666,
 'toes': 36988,
 'numb': 25513,
 'step': 34399,
 'boot': 4851,
 'wanderingim': 39404,
 'ready': 29302,
 'anywhere': 1856,
 'own': 26919,
 'parade': 27122,
 'spell': 33849,
 'promise': 28647,
 'under': 38324,
 'ithey': 18838,
 'year': 41418,
 'octobers': 25620,
 'drifting': 10957,
 'mays': 22525,
 'set': 31883,
 'sail': 30954,
 'tide': 36625,
 'comes': 7538,
 'fate': 12702,
 'wind': 40390,
 'shift': 32194,
 'course': 8154,
 'breeze': 5242,
 'upwind': 38730,
 'memories': 22887,
 'empty': 11625,
 'best': 4063,
 'friend': 14041,
 'fall': 12529,
 'right': 30096,
 'moment': 23736,
 'hug': 17731,
 'whats': 39976,
 'pussycat': 28896,
 'woah': 40582,
 'woahpussycat': 40589,
 'lots': 21494,
 'spend': 33856,
 'powder': 28355,
 'cute': 8684,
 'nosepussycat': 25256,
 'nosewhats': 25258,
 'thrilling': 36482,
 'willing': 40355,
 'eyespussycat': 12362,
 'eyeswhats': 12383,
 'delicious': 9449,
 'wishes': 40513,
 'soon': 33595,
 'kissing': 19783,
 'lipspussycat': 21058,
 'nose': 25249,
 'eastern': 11291,
 'explodin': 12255,
 'violence': 39116,
 'flarin': 13290,
 'bullets': 5532,
 'loadin': 21189,
 'kill': 19703,
 'votin': 39222,
 'believe': 3877,
 'war': 39466,
 'gun': 15860,
 'totin': 37370,
 'jordan': 19375,
 'river': 30286,
 'bodies': 4698,
 'floatinbut': 13388,
 'eve': 11996,
 'destructiondont': 9666,
 'fears': 12756,
 'button': 5725,
 'pushed': 28885,
 'running': 30788,
 'therell': 36170,
 'none': 25192,
 'save': 31170,
 'grave': 15567,
 'boy': 5027,
 'bound': 4983,
 'scare': 31352,
 'boyand': 5028,
 'destructionyeah': 9668,
 'bloods': 4563,
 'mad': 21997,
 'feels': 12819,
 'coagulatin': 7350,
 'sittin': 32770,
 'contemplatin': 7852,
 'twist': 38081,
 'truth': 37834,
 'knows': 19970,
 'regulation': 29583,
 'handful': 16101,
 'senators': 31788,
 'pass': 27232,
 'legislationand': 20574,
 'marches': 22308,
 'integration': 18509,
 'human': 17772,
 'respect': 29862,
 'disintegratin': 10095,
 'crazy': 8259,
 'frustratinand': 14168,
 'destructionthink': 9667,
 'hate': 16317,
 'china': 6846,
 'selma': 31777,
 'alabama': 1115,
 'four': 13864,
 'space': 33754,
 'placethe': 27867,
 'drums': 11050,
 'pride': 28541,
 'disgrace': 10079,
 'bury': 5642,
 'dead': 9221,
 'trace': 37480,
 'next': 24818,
 'neighbor': 24741,
 'graceand': 15491,
 'destruction': 9665,
 'sloopy': 33071,
 'lives': 21133,
 'bad': 3088,
 'everybody': 12039,
 'tries': 37675,
 'daddy': 8755,
 'singing': 32685,
 'hair': 16019,
 'shake': 31988,
 'driving': 10997,
 'ticket': 36606,
 'ride': 30056,
 'living': 21149,
 'bringing': 5296,
 'free': 13949,
 'riding': 30087,
 'ought': 26631,
 'gets': 14592,
 'saying': 31246,
 'roses': 30595,
 'blue': 4608,
 'lady': 20146,
 'mister': 23603,
 'florist': 13437,
 'order': 26555,
 'silly': 32626,
 'quarrel': 28943,
 'hope': 17528,
 'chase': 6647,
 'send': 31789,
 'sweetest': 35367,
 'gal': 14356,
 'trick': 37661,
 'white': 40090,
 'orchid': 26554,
 'gown': 15470,
 'sister': 32762,
 'papas': 27103,
 'swing': 35402,
 'hip': 17125,
 'breed': 5240,
 'drag': 10813,
 'brand': 5128,
 'bagcome': 3134,
 'mama': 22133,
 'scene': 31373,
 'hes': 16870,
 'fancy': 12593,
 'line': 20991,
 'clean': 7120,
 'baghes': 3142,
 'doing': 10308,
 'fly': 13483,
 'cheap': 6668,
 'shy': 32472,
 'monkey': 23818,
 'mashed': 22401,
 'jump': 19452,
 'jack': 19012,
 'later': 20341,
 'alligatorcome': 1251,
 'bag': 3133,
 'purpose': 28872,
 'woman': 40620,
 'start': 34233,
 'game': 14381,
 ...}

In [83]:
count_vect.inverse_transform(lyrics_mat[0])

[array(['be', 'mean', 'lyrics', 'so', 'l7', 'square', 'rough', 'form',
        'they', 'typed', 'when', '7', 'number', 'l', 'letter', 'lseven',
        'with', 'wool', 'pull', 'really', 'someone', 'you', 'get', 'do',
        'thats', 'dance', 'to', 'learn', 'come', 'belseven', 'not',
        'chance', 'no', 'take', 'dont', 'lets', 'jaw', 'and', 'horns',
        'big', 'had', 'saw', 'she', 'thing', 'a', 'about', 'hatty', 'told',
        'matty', 'quatro', 'tres', 'two', 'one', 'dos', 'uno', 'samudio',
        'domingo', 'pharaohs', 'bully', 'wooly', 'miscellaneous', 'sham',
        'the', 'sam'], dtype='<U46')]

#### find top k words

below cell go over the entire matrix (~5000*40000 ~200 millions operations), takes ~1 minutes

In [140]:
word_count = dict()
for i in range(lyrics_mat.toarray().shape[0]):
    curr = list(lyrics_mat[i].toarray()[0])
    for wi in range(len(curr)):
        if curr[wi] > 0:
            if wi not in word_count:
                word_count[wi] = curr[wi]
            else:
                word_count[wi] += curr[wi]

In [144]:
k = 10

keys_list = list(word_count.keys())
counts_list = list(word_count.values())
argsorted_count = np.argsort(counts_list)

top_k_word = []
top_k_count = []
bot_k_word = []
bot_k_count = []

for i in range(k):
    bot_k_word.append(count_vect.get_feature_names()[keys_list[argsorted_count[i]]])
    bot_k_count.append(counts_list[argsorted_count[i]])
for i in range(1,k+1):
    top_k_word.append(count_vect.get_feature_names()[keys_list[argsorted_count[-i]]])
    top_k_count.append(counts_list[argsorted_count[-i]])

print("Top\tWord\tCount")
for i in range(k):
    print(str(i+1)+"\t"+top_k_word[i]+"\t\t"+str(top_k_count[i]))
    
print("Bottom\tWord\t\tCount")
for i in range(k):
    print(str(i+1)+"\t"+bot_k_word[i]+"\t"+str(bot_k_count[i]))

Top	Word	Count
1	you		64606
2	i		56514
3	the		53451
4	to		35752
5	and		32555
6	me		31170
7	a		29282
8	it		25688
9	my		22821
10	in		18553
Bottom	Word		Count
1	thereacross	1
2	sleepsjust	1
3	sleepsit	1
4	sleepsi	1
5	cleanit	1
6	cleanill	1
7	wellmm	1
8	selfcentered	1
9	seea	1
10	seagram	1

### Apply Tf-Idf

source: https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction


source: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html#sklearn.feature_extraction.text.TfidfTransformer

The goal of using tf-idf instead of the raw frequencies of occurrence of a token in a given document is to scale down the impact of tokens that occur very frequently in a given corpus and that are hence empirically less informative than features that occur in a small fraction of the training corpus.

The formula that is used to compute the tf-idf for a term t of a document d in a document set is tf-idf(t, d) = tf(t, d) * idf(t), and the idf is computed as idf(t) = log [ n / df(t) ] + 1 (if smooth_idf=False), where n is the total number of documents in the document set and df(t) is the document frequency of t; the document frequency is the number of documents in the document set that contain the term t. The effect of adding “1” to the idf in the equation above is that terms with zero idf, i.e., terms that occur in all documents in a training set, will not be entirely ignored. (Note that the idf formula above differs from the standard textbook notation that defines the idf as idf(t) = log [ n / (df(t) + 1) ]).

In [131]:
transformer = TfidfTransformer()
tfidf_mat = transformer.fit_transform(lyrics_mat)

In [132]:
transformer.idf_

array([8.80669637, 8.80669637, 8.80669637, ..., 8.80669637, 6.4088011 ,
       8.11354919])

Note: idf - the higher the more useful the word is (less frequent in other document)

#### find top k words

below cell go over the entire matrix (~5000*40000 ~200 millions operations), takes ~1 minutes

In [145]:
tfidf_count = dict()
for i in range(tfidf_mat.toarray().shape[0]):
    curr = list(tfidf_mat[i].toarray()[0])
    for wi in range(len(curr)):
        if curr[wi] > 0:
            if wi not in tfidf_count:
                tfidf_count[wi] = curr[wi]
            else:
                tfidf_count[wi] += curr[wi]

In [146]:
k = 10

keys_list = list(tfidf_count.keys())
counts_list = list(tfidf_count.values())
argsorted_count = np.argsort(counts_list)

top_k_word = []
top_k_count = []
bot_k_word = []
bot_k_count = []

for i in range(k):
    bot_k_word.append(count_vect.get_feature_names()[keys_list[argsorted_count[i]]])
    bot_k_count.append(counts_list[argsorted_count[i]])
for i in range(1,k+1):
    top_k_word.append(count_vect.get_feature_names()[keys_list[argsorted_count[-i]]])
    top_k_count.append(counts_list[argsorted_count[-i]])

print("Top\tWord\tCount")
for i in range(k):
    print(str(i+1)+"\t"+top_k_word[i]+"\t"+str(top_k_count[i]))
    
print("Bottom\tWord\t\tCount")
for i in range(k):
    print(str(i+1)+"\t"+bot_k_word[i]+"\t\t"+str(bot_k_count[i]))

Top	Word	Count
1	you	544.550865358322
2	i	485.692936922662
3	the	411.68270345703814
4	to	298.62608717206115
5	me	282.03058257911346
6	and	272.4908298336047
7	a	243.1203736606626
8	it	221.47677805701213
9	my	218.8723947203573
10	love	201.53706475639328
Bottom	Word		Count
1	wre		0.006070876886015375
2	thoingwe		0.006070876886015375
3	thoingto		0.006070876886015375
4	thoingnow		0.006070876886015375
5	thoiathoiathoing		0.006070876886015375
6	crys		0.006070876886015375
7	clubnow		0.006070876886015375
8	sum		0.006070876886015375
9	godly		0.008965238853695262
10	hollerinay		0.008965238853695262

## Testing things out, ignore below

Using TfidfVectorizer()

source: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html#sklearn.feature_extraction.text.TfidfVectorizer.get_stop_words

In [28]:
tfidf_vect = TfidfVectorizer()
tfidf_mat = tfidf_vect.fit_transform(lyrics_data)
tfidf_mat.toarray().shape

(4913, 42123)

In [33]:
len(tfidf_vect.idf_)

42123

In [34]:
len(tfidf_vect.vocabulary_)

42123

In [44]:
len(tfidf_vect.get_feature_names())

42123

now we know TfidfVectorizer.idf_ maps to either TfidfVectorizer.vocabulary_ or TfidfVectorizer.get_feature_names(), need to find out which one so we can get the top k / bottom k words with highest/lowest idf

In [98]:
test_vect = CountVectorizer()
corpus = ["the the the", "the an an", "the an important"]
test_vect.fit_transform(corpus)
# test_vect.idf_

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [99]:
test_vect.get_feature_names()

['an', 'important', 'the']

In [100]:
test_vect.vocabulary_

{'an': 0, 'important': 1, 'the': 2}

In [116]:
test_vect.transform(["the the the"]).toarray()

array([[0, 0, 3]], dtype=int64)

we now know the TfidfVectorizer.idf_ is mapped to TfidfVectorizer.get_feature_names()

TfidfVectorizer.vocabulary_ is a mapping of terms to feature indices instead of a mapping of terms to term frequencies, I misunderstood

now wanna figure out what does preprocessor, analyzer and tokenizer of CountVectorizer do

In [77]:
test_vect = CountVectorizer(ngram_range=(1,2),token_pattern=r'\b\w+\b')
corpus = ["the the the", "the an an", "the an important"]
preprocessor = test_vect.build_preprocessor()
tokenizer = test_vect.build_tokenizer()
analyzer = test_vect.build_analyzer()

preprocessor("  the an  important  !@#@! 123 1 ! .? ")

'  the an  important  !@#@! 123 1 ! .? '

In [78]:
tokenizer("  the an a important  !@#@! 123 1 ! .? ")

['the', 'an', 'a', 'important', '123', '1']

In [79]:
analyzer("  the an a important  !@#@! 123 1 ! .? ")

['the',
 'an',
 'a',
 'important',
 '123',
 '1',
 'the an',
 'an a',
 'a important',
 'important 123',
 '123 1']